parameters:
  ptyhard_json_schema_bundle.schema_annotation_priority: 30
  ptyhard_json_schema_bundle.request_validation_priority: -100
  ptyhard_json_schema_bundle.response_validation_priority: 20
  ptyhard_json_schema_bundle.exception_listener_priority: 20

services:

    Ptyhard\JsonSchemaBundle\EventListener\ExceptionListener:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: '%ptyhard_json_schema_bundle.exception_listener_priority%' }

    Ptyhard\JsonSchemaBundle\EventListener\SchemaFileValidationListener:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.controller  }
            - { name: kernel.event_listener, event: kernel.view }

    # schema generator
    Ptyhard\JsonSchemaBundle\Generator\Schema\Generators\FileGenerator:
      autowire: true
      arguments:
        $baseFilePath: '%json_schema_bundle.json_file_directory%'

    Ptyhard\JsonSchemaBundle\Generator\Schema\SchemaGeneratorResolver:
      arguments:
        $generators:
          - '@Ptyhard\JsonSchemaBundle\Generator\Schema\Generators\FileGenerator'


    Ptyhard\JsonSchemaBundle\Validator\Validator:
        autowire: true

    Ptyhard\JsonSchemaBundle\Validator\ValidatorInterface: '@Ptyhard\JsonSchemaBundle\Validator\Validator'
