parameters:
  ptyhard_json_schema_bundle.schema_annotation_priority: 30
  ptyhard_json_schema_bundle.request_validation_priority: -100
  ptyhard_json_schema_bundle.response_validation_priority: 20
  ptyhard_json_schema_bundle.exception_listener_priority: 20

services:

    Ptyhard\JsonSchemaBundle\EventListener\ExceptionListener:
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: '%ptyhard_json_schema_bundle.exception_listener_priority%' }

    Ptyhard\JsonSchemaBundle\EventListener\SchemaObjectValidationListener:
        autowire: true
        tags:
          - { name: kernel.event_listener, event: kernel.controller_arguments}
          - { name: kernel.event_listener, event: kernel.view }

    # property generator

    Ptyhard\JsonSchemaBundle\Generator\Property\PropertyGeneratorResolver:
        autowire: true
        arguments:
            $generators:
                - '@Ptyhard\JsonSchemaBundle\Generator\Property\Generators\DefaultPropertyGenerator'
                - '@Ptyhard\JsonSchemaBundle\Generator\Property\Generators\CollectionPropertyGenerator'

    Ptyhard\JsonSchemaBundle\Generator\Property\Generators\DefaultPropertyGenerator:
        autowire: true
        arguments:
            $supported:
                - 'Ptyhard\JsonSchemaBundle\Annotations\Property\StringProperty'
                - 'Ptyhard\JsonSchemaBundle\Annotations\Property\NumberProperty'
                - 'Ptyhard\JsonSchemaBundle\Annotations\Property\ObjectProperty'
                - 'Ptyhard\JsonSchemaBundle\Annotations\Property\ArrayProperty'

    Ptyhard\JsonSchemaBundle\Generator\Property\Generators\CollectionPropertyGenerator:
        autowire: true

    # schema generator

    Ptyhard\JsonSchemaBundle\Generator\Schema\Generators\ObjectSchemaGenerator:
        autowire: true

    Ptyhard\JsonSchemaBundle\Generator\Schema\Generators\FileGenerator:
        autowire: true
        arguments:
            $cache: '@ptyhard.json_schema_bundle.cache'
            $baesFilePath: '%json_schema_bundle.json_file_directory%'

    Ptyhard\JsonSchemaBundle\Generator\Schema\SchemaGeneratorResolver:
        arguments:
            $generators:
              - '@Ptyhard\JsonSchemaBundle\Generator\Schema\Generators\ObjectSchemaGenerator'
              - '@Ptyhard\JsonSchemaBundle\Generator\Schema\Generators\FileGenerator'

    ptyhard.json_schema_bundle.cache:
        class: Symfony\Component\Cache\Simple\FilesystemCache

    # Generator
    Ptyhard\JsonSchemaBundle\Generator\Generator:
        autowire: true
        calls:
            - method: setSchemaGeneratorResolver
              arguments:
                  - '@Ptyhard\JsonSchemaBundle\Generator\Schema\SchemaGeneratorResolver'
            - method: setPropertyGeneratorResolver
              arguments:
                  - '@Ptyhard\JsonSchemaBundle\Generator\Property\PropertyGeneratorResolver'


    Ptyhard\JsonSchemaBundle\Validator\Validator:
        autowire: true

    Ptyhard\JsonSchemaBundle\SchemaObject\Exporter:
        autowire: true

    Ptyhard\JsonSchemaBundle\SchemaObject\Factory:
        autowire: true

    Ptyhard\JsonSchemaBundle\SchemaObject\Checker:
        autowire: true

    Ptyhard\JsonSchemaBundle\ArgumentResolver\SchemaClassResolver:
        autowire: true
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    Ptyhard\JsonSchemaBundle\Validator\ValidatorInterface: '@Ptyhard\JsonSchemaBundle\Validator\Validator'
    Ptyhard\JsonSchemaBundle\SchemaObject\FactoryInterface: '@Ptyhard\JsonSchemaBundle\SchemaObject\Factory'
    Ptyhard\JsonSchemaBundle\SchemaObject\ExporterInterface: '@Ptyhard\JsonSchemaBundle\SchemaObject\Exporter'
    Ptyhard\JsonSchemaBundle\SchemaObject\CheckerInterface: '@Ptyhard\JsonSchemaBundle\SchemaObject\Checker'
    Ptyhard\JsonSchemaBundle\Generator\GeneratorInterface: '@Ptyhard\JsonSchemaBundle\Generator\Generator'
