name: CI

on: ['push']
jobs:
  php-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run composer install
        run: |
          composer install
      - name: Run test
        run: composer tests