name: CI

on: ['push']
jobs:
  php-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4', '8.0']
    steps:
      - uses: actions/checkout@v1
      - name: Run composer install
        run: |
          composer install
      - name: Run test
        run: composer tests
